import {
  AnimationState,
  BlendPriority,
  type AnimationSpec,
  easeInOutCubic,
  snapCurve,
} from "./types";

function spec(
  state: AnimationState,
  priority: BlendPriority,
  duration: number,
  looping: boolean,
  params: Record<string, number>,
  physics: { gravity: number; damping: number; tension: number; elasticity: number },
  transitionIn: { duration: number; easing: (t: number) => number },
  transitionOut: { duration: number; easing: (t: number) => number },
  interruptible: boolean,
): AnimationSpec {
  return { state, priority, duration, looping, params, physics, transitionIn, transitionOut, interruptible };
}

const BEZIER = easeInOutCubic;
const SNAP = snapCurve;

export const ANIMATIONS: AnimationSpec[] = [
  spec(AnimationState.Idle, BlendPriority.Base, 8, true,
    { ParamBreath: 0.5, ParamMouthForm: 0.25, ParamEyeLOpen: 1, ParamEyeROpen: 1, ParamCoreGlow: 0.3 },
    { gravity: 0.9, damping: 0.85, tension: 0.9, elasticity: 0.5 },
    { duration: 0.8, easing: BEZIER },
    { duration: 0.8, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Talking, BlendPriority.HighAction, 0, false,
    { ParamMouthForm: 0.35, ParamMouthOpenY: 0.5, ParamAngleZ: 2, ParamCoreGlow: 0.6 },
    { gravity: 1, damping: 0.8, tension: 0.95, elasticity: 0.6 },
    { duration: 0.1, easing: BEZIER },
    { duration: 0.4, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Reading, BlendPriority.Workflow, 4.5, true,
    { ParamAngleY: -12, ParamBodyAngleY: 4, ParamEyeBallX: 0.8, ParamEyeLOpen: 0.85, ParamEyeROpen: 0.85, ParamMouthForm: 0 },
    { gravity: 1.2, damping: 0.9, tension: 0.7, elasticity: 0.3 },
    { duration: 0.6, easing: BEZIER },
    { duration: 0.6, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Thinking, BlendPriority.Workflow, 4, true,
    { ParamAngleY: 6, ParamAngleZ: 4, ParamEyeBallX: 0.4, ParamEyeBallY: 0.6, ParamMouthForm: -0.15, ParamCoreGlow: 0.5 },
    { gravity: 1, damping: 0.85, tension: 0.8, elasticity: 0.6 },
    { duration: 1, easing: BEZIER },
    { duration: 1, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Greeting, BlendPriority.Interrupt, 3.5, false,
    { ParamAngleY: -25, ParamBodyAngleY: -8, ParamEyeLOpen: 0, ParamEyeROpen: 0, ParamMouthForm: 0.6 },
    { gravity: 1.3, damping: 0.75, tension: 0.6, elasticity: 0.4 },
    { duration: 0.4, easing: BEZIER },
    { duration: 0.8, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Wake, BlendPriority.Interrupt, 3, false,
    { ParamAngleY: 5, ParamBodyAngleY: 3, ParamEyeLOpen: 1, ParamEyeROpen: 1, ParamCoreGlow: 1.5, ParamMouthForm: 0.3 },
    { gravity: 1, damping: 0.6, tension: 1.4, elasticity: 0.8 },
    { duration: 0.4, easing: BEZIER },
    { duration: 0.4, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Sleep, BlendPriority.Base, 12, true,
    { ParamAngleY: -8, ParamAngleZ: -5, ParamEyeLOpen: 0, ParamEyeROpen: 0, ParamBodyAngleY: -3, ParamBreath: 0.25, ParamCoreGlow: 0.15, ParamMouthForm: 0 },
    { gravity: 1.2, damping: 0.95, tension: 0.3, elasticity: 0.2 },
    { duration: 2.5, easing: BEZIER },
    { duration: 2.5, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Embarrassed, BlendPriority.HighAction, 4, false,
    { ParamAngleX: -18, ParamAngleZ: -8, ParamBodyAngleX: -5, ParamBlush: 1, ParamCoreGlow: 0.8 },
    { gravity: 1, damping: 0.5, tension: 1.2, elasticity: 0.9 },
    { duration: 0.15, easing: BEZIER },
    { duration: 3, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Happy, BlendPriority.HighAction, 2.5, false,
    { ParamBodyAngleY: 6, ParamAngleZ: 12, ParamEyeLSmile: 1, ParamEyeRSmile: 1, ParamMouthForm: 1, ParamCoreGlow: 0.9, ParamBlush: 0.4 },
    { gravity: 0.9, damping: 0.6, tension: 1.1, elasticity: 0.9 },
    { duration: 0.3, easing: BEZIER },
    { duration: 0.3, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Confused, BlendPriority.Workflow, 3.8, true,
    { ParamAngleZ: -14, ParamAngleY: 5, ParamBodyAngleZ: 4, ParamMouthForm: -0.2, ParamCoreGlow: 0.4 },
    { gravity: 1, damping: 0.9, tension: 0.5, elasticity: 0.3 },
    { duration: 0.7, easing: BEZIER },
    { duration: 0.7, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Error, BlendPriority.Emergency, 3, true,
    { ParamBodyAngleY: -6, ParamGlitch: 0.8, ParamEyeLOpen: 1, ParamEyeROpen: 1, ParamMouthForm: -0.8, ParamCoreGlow: 1.2 },
    { gravity: 1, damping: 0.3, tension: 0.9, elasticity: 0.2 },
    { duration: 0.05, easing: SNAP },
    { duration: 0.05, easing: SNAP },
    false,
  ),
  spec(AnimationState.Coding, BlendPriority.HighAction, 2, true,
    { ParamHoloHUD: 0.8, ParamEyeBallX: 0.4, ParamMouthForm: 0.3, ParamCoreGlow: 0.7 },
    { gravity: 1, damping: 0.9, tension: 0.8, elasticity: 0.3 },
    { duration: 0.2, easing: BEZIER },
    { duration: 0.2, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Compiling, BlendPriority.Workflow, 3, true,
    { ParamEyeLSmile: 1, ParamEyeRSmile: 1, ParamAngleY: -2, ParamCoreGlow: 1, ParamBreath: 0.3 },
    { gravity: 0.1, damping: 0.95, tension: 0.4, elasticity: 0.5 },
    { duration: 1, easing: BEZIER },
    { duration: 1, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Debugging, BlendPriority.Workflow, 4, true,
    { ParamBodyAngleY: 8, ParamAngleZ: -5, ParamEyeLOpen: 0.6, ParamEyeROpen: 0.6, ParamCoreGlow: 0.8 },
    { gravity: 1, damping: 0.95, tension: 0.5, elasticity: 0.2 },
    { duration: 0.8, easing: BEZIER },
    { duration: 0.8, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Searching, BlendPriority.Workflow, 3, true,
    { ParamAngleX: 20, ParamHoloHUD: 0.6, ParamCoreGlow: 0.5, ParamMouthForm: 0.15 },
    { gravity: 1, damping: 0.92, tension: 0.4, elasticity: 0.5 },
    { duration: 0.6, easing: BEZIER },
    { duration: 0.6, easing: BEZIER },
    true,
  ),
  spec(AnimationState.Notification, BlendPriority.Emergency, 1.5, false,
    { ParamBodyAngleY: 5, ParamEyeLOpen: 1, ParamEyeROpen: 1, ParamMouthForm: 0.3, ParamCoreGlow: 0.8 },
    { gravity: 1, damping: 0.3, tension: 1.3, elasticity: 0.7 },
    { duration: 0.05, easing: SNAP },
    { duration: 0.05, easing: SNAP },
    true,
  ),
];

export const SPEC_MAP = new Map<AnimationState, AnimationSpec>(
  ANIMATIONS.map((a) => [a.state, a]),
);

export const BASE_SPEC = SPEC_MAP.get(AnimationState.Idle)!;
